### ISSUE TITLE
Error when adding some twitter user to target 

### ISSUE THREAD

**Issue by micheleminno** [micheleminno/real-affinities#12]
Happening i.e with accounts: @micheleminno, @cz_binance
Error when updating friends of the user, after having updated his followers.

**Comment by micheleminno** [comment]
On terminal:

`Err: {"message":"Sorry, that page does not exist.","code":34,"allErrors":[{"code":34,"message":"Sorry, that page does not exist."}],"twitterReply":{"errors":[{"code":34,"message":"Sorry, that page does not exist."}]},"statusCode":404}

ci-express-1        | User doesn't exist on Twitter

ci-express-1        | setResult(null, 1, -1, followers, callback)

ci-express-1        | User null

ci-express-1        | Followers affinities updated

ci-express-1        | User id null

ci-express-1        | Affinities added for user 797856405021687800

ci-express-1        | /usr/src/app/server/target.js:46

ci-express-1        |       					+ data["followers"]["page"] + ", "

ci-express-1        |       					                   ^

ci-express-1        |

ci-express-1        | TypeError: Cannot read property 'page' of undefined

ci-express-1        |     at /usr/src/app/server/target.js:46:31

ci-express-1        |     at /usr/src/app/server/affinities.js:305:6

ci-express-1        |     at setResult (/usr/src/app/server/affinities.js:124:3)

ci-express-1        |     at /usr/src/app/server/affinities.js:195:16`

**Comment by micheleminno** [comment]
This error happens when clicking on the button, not when entering by keyboard.
